### ISSUE TITLE
Where are the project files?

### ISSUE THREAD

**Issue by janvsc** [saravanan75/django_pluralsight#1]
I only see manage.py
Where is the rest.

Several imports are done and not shown in the video

Please fix

**Comment by saravanan75** [comment]
There are four different branches that were created that has the files that are specific to that modules. Please switch to module specific branches.

**Comment by janvsc** [comment]
Missing files in Module 4
Example:
views are changed in the video of module 4 but no views file in module 4 on github

**Comment by janvsc** [comment]
Changes to list.html also not present (cookies). How many times visited

**Comment by janvsc** [comment]
Updated all the files from module 3 and module 4 and getting many errors

**Comment by Vishwakanth7662** [comment]
facing session management issues. Please update all module4 files in github.

**Comment by saravanan75** [comment]
Hi VIshwakanth,

Thanks for bringing this to my attention. I have uploaded the missing
files. I didn't have time to run through testing. Please let me know if you
see any issues.

Thanks,
Saravanan
