### ISSUE TITLE
Missing Module 5 and files

### ISSUE THREAD

**Issue by Vishwakanth7662** [saravanan75/django_pluralsight#2]
Not able to find module 5 files such as default.html and also having a hard time to get translation work. 
I have downloaded zip files from the site and extracted them at same location.
I have never worked with path variables before. So, could you help me out here.

**Comment by saravanan75** [comment]
Hi Vishwakanth,

module 5 in the course corresponds to module 4 in github (as module 1 in
pluralsight is a short 90 seconds intro which doesn't have any exercise).

Somehow my template directory was part of .gitignore. I have manually
pushed this directory which has the default.html file.

Here are the instructions to add a path variable.
If you are using WIndows, click on the windows start icon -> search for
"environment variables" -> Click on environment variables -> select Path
from the user variables -> Click Edit and add the location of the bin
directory here.

If you are using linux, you will use export PATH=/path/to/bin:$PATH

Hope this helps.

Thanks,
Saravanan

**Comment by saravanan75** [comment]
Missing files updated.
